name: Aqua Security Image Scan

on: [push]  # Trigger on every push (modify as needed)

jobs:
  aqua_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Aqua Scanner Image
        run: docker pull registry.aquasec.com/scanner:latest-saas

      - name: Scan Docker Image with Aqua
        run: |
          docker run --rm -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock \
            registry.aquasec.com/scanner:latest-saas scan \
            --registry "Docker Hub" \
            --image $IMAGE_NAME \
            --host https://uniqueid.cloud.aquasec.com/ \
            --user $AQUA_USERNAME \
            --password $AQUA_PASSWORD \
            --show-negligible \
            --htmlfile /tmp/out.html \
            --jsonfile /tmp/out.json > /dev/null
        env:
          AQUA_USERNAME: ${{ secrets.AQUA_USERNAME }}
          AQUA_PASSWORD: ${{ secrets.AQUA_PASSWORD }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

      - name: Upload Scan Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AquaScanResults
          path: |
            /tmp/out.html
            /tmp/out.json
