name: Aqua Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    env:
      BUILD_JOB_NAME: MY_PROJECT_NAME
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: echo "IMAGE_NAME=${{ secrets.IMAGE_NAME }}"

      - name: Pull Aqua Scanner Image
        run: docker pull registry.aquasec.com/scanner:latest-saas

      - name: Run Aqua Scanner
        run: |
          docker run --rm -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock \
            -e BUILD_JOB_NAME=$BUILD_JOB_NAME \
            -e BUILD_NUMBER=$BUILD_NUMBER \
            registry.aquasec.com/scanner:latest-saas scan \
            --registry "Docker Hub" \
            --image-name "${{ secrets.IMAGE_NAME }}" \
            --host "${{ secrets.AQUA_HOST }}" \
            --user "${{ secrets.AQUA_U }}" \
            --password "${{ secrets.AQUA_PASS }}" \
            --show-negligible \
            --htmlfile /tmp/out.html \
            --jsonfile /tmp/out.json

      - name: Upload Scan Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: aqua-scan-report
          path: /tmp/out.html

      - name: Upload Scan Report (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: aqua-scan-report-json
          path: /tmp/out.json
