name: Aqua Security Image Scan

on:
  push:
    branches:
      - main  # Runs scan on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILD_JOB_NAME: MY_PROJECT_NAME
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Aqua Registry
        run: echo "${{ secrets.AQUA_PASSWORD }}" | docker login registry.aquasec.com -u "${{ secrets.AQUA_USERNAME }}" --password-stdin

      - name: Pull Aqua Scanner Image
        run: docker pull registry.aquasec.com/scanner:latest-saas

      - name: Run Aqua Scanner
        run: |
          docker run --rm -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock \
            -e BUILD_JOB_NAME=$BUILD_JOB_NAME \
            -e BUILD_NUMBER=$BUILD_NUMBER \
            registry.aquasec.com/scanner:latest-saas scan \
            --registry "Docker Hub" \
            --image-name "mongo:latest" \
            --host "https://uniqueid.cloud.aquasec.com/" \
            --user "${{ secrets.AQUA_U }}" \
            --password "${{ secrets.AQUA_PASS }}" \
            --show-negligible \
            --htmlfile /tmp/out.html \
            --jsonfile /tmp/out.json > /dev/null

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: AquaScanResults
          path: |
            /tmp/out.html
            /tmp/out.json
