name: Aqua Security Image Scan

on:
  push:
    branches:
      - main  # Runs scan on pushes to the main branch

jobs:
  aqua_scan:
    runs-on: ubuntu-latest

    steps:
      # 🔹 Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 🔹 Set Build Variables for Aqua UI
      - name: Set Build Variables
        run: |
          echo "BUILD_JOB_NAME=GitHub Actions Scan" >> $GITHUB_ENV
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      # 🔹 Authenticate with Aqua Registry
      - name: Authenticate with Aqua Registry
        run: echo "${{ secrets.AQUA_PASSWORD }}" | docker login registry.aquasec.com -u "${{ secrets.AQUA_USERNAME }}" --password-stdin

      # 🔹 Pull Aqua Scanner Image
      - name: Pull Aqua Scanner Image
        run: docker pull registry.aquasec.com/scanner:latest-saas

      # 🔹 Run Aqua Scanner
      - name: Scan Docker Image with Aqua Scanner
        run: |
          docker run --rm -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock \
            registry.aquasec.com/scanner:latest-saas scan \
            --registry "Docker Hub" \
            --image-name "${{ secrets.IMAGE_NAME }}" \
            --host "${{ secrets.AQUA_HOST }}" \
            --user "${{ secrets.AQUA_USERNAME }}" \
            --password "${{ secrets.AQUA_PASSWORD }}" \
            --show-negligible \
            --htmlfile /tmp/out.html \
            --jsonfile /tmp/out.json \
            --build-job-name "$BUILD_JOB_NAME" \
            --build-number "$BUILD_NUMBER" > /dev/null

      # 🔹 Upload Scan Results as Artifacts
      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: AquaScanResults
          path: |
            /tmp/out.html
            /tmp/out.json
