name: Aqua Image Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      BUILD_JOB_NAME: MY_PROJECT_NAME
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Aqua Registry
      run: |
        echo "${{ secrets.AQUA_PASSWORD }}" | docker login registry.aquasec.com -u ${{ secrets.AQUA_USERNAME }} --password-stdin

    - name: Pull Aqua Scanner Image
      run: docker pull registry.aquasec.com/scanner:latest-saas

    - name: Run Aqua Scanner
      run: |
        docker run --rm \
          -v "${GITHUB_WORKSPACE}:/scan" \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -e BUILD_JOB_NAME="${{ env.BUILD_JOB_NAME }}" \
          -e BUILD_NUMBER="${{ env.BUILD_NUMBER }}" \
          registry.aquasec.com/scanner:latest-saas scan \
          "${{ secrets.IMAGE_NAME }}" \
          --registry "Docker Hub" \
          --host "${{ secrets.AQUA_HOST }}" \
          --user "${{ secrets.AQUA_U }}" \
          --password "${{ secrets.AQUA_PASS }}" \
          --show-negligible \
          --htmlfile /scan/out.html \
          --jsonfile /scan/out.json || exit 1

    - name: Upload Aqua Scan Reports
      uses: actions/upload-artifact@v4
      with:
        name: AquaScanReports
        path: |
          ${{ github.workspace }}/out.html
          ${{ github.workspace }}/out.json
